name: Push to main
on:
  push:
    branches:
      - main

jobs:
  run-sonarqube-scan:
    name: Run SonarQube Scan
    uses: ./.github/workflows/sonarqube.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
