name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Create semantic release
        uses: cocogitto/cocogitto-action@c7a74f5406bab86da17da0f0e460a69f8219a68c # v3.11
        id: release
        with:
          release: true
          git-user: 'github-actions[bot]'
          git-user-email: 'github-actions[bot]@users.noreply.github.com'
          check-latest-tag-only: true

      - name: Push semantic version tag
        run: git push --follow-tags && git push --tags
        shell: bash

      - name: Create GitHub release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          tag_name: ${{ steps.release.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Log release info
        run: |
          echo "New release created: ${{ steps.release.outputs.version }}"